<?php 
// -- Controllers
$c[1] = 'Tema site-ului';
$c[2] = 'Setările temei %1';

// -- Models
$m[1] = 'Temă';
$m[2] = 'Informații';
$m[3] = 'Acțiuni';
$m[4] = 'de';
$m[5] = 'Activează tema "%1"';
$m[6] = 'Setări';
$m[7] = 'Dezinstalează';
$m[8] = 'Resetează';
$m[9] = 'Acest pachet nu este instalat. Dimensiune: <i>%1KB</i>';
$m[10] = 'Instalează';
$m[11] = 'Șterge';
$m[12] = 'Temă invalidă. Plasează fișierul info.ini în folderul temei tale.';
$m[13] = 'Fișierul tău info.ini nu este formatat corect.';
$m[14] = 'Trebuie să incluzi cheile "name" și "description" în fișierul tău info.ini.';
$m[15] = 'Trebuie să incluzi cheia "about" în fișierul tău info.ini.';
$m[16] = 'Folderul "%1" nu a fost găsit.';
$m[17] = 'A fost instalată cu succes tema "%1".';
$m[18] = 'A fost resetată cu succes tema "%1".';
$m[19] = 'Nu poți elimina tema implicită.';
$m[20] = 'A fost dezinstalată cu succes tema "%1".';
$m[21] = 'Nu a putut fi înlăturat folderul "%1".';
$m[22] = 'Tema de dezinstalat "%1" este invalidă.';
$m[23] = 'Tema "%1" este deja activă.';
$m[24] = 'A fost activată cu succes tema "%1".';
$m[25] = 'Tema "%1" nu a fost găsită.';
$m[26] = 'Au fost actualizate cu succes setările pentru tema "%1".';
$m[27] = 'Nu există setări de configurat pentru tema "%1".';
$m[28] = 'Ești sigur că vrei să resetezi tema "%1" la valorile implicite? Vor fi recitite informațiile din fișierul info.ini al temei.';
$m[29] = 'Ești sigur că vrei să activezi tema %1?';
$m[30] = 'Ești sigur că vrei să dezinstalezi tema "%1"?';

// -- Views
$v[1] = 'Organizează temele site-ului tău';
$v[2] = 'Setările temei "%1"';
$v[3] = '(valori delimitate de virgulă)';
$v[4] = 'Actualizează';
$v[5] = 'Nu ai specificat nicio setare în fișierul info.ini al temei tale.';